apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: penguin
  name: penguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penguin
  template:
    metadata:
      labels:
        app: penguin
    spec:
      containers:
      - image: kareemelkasaby/itimanspenguin:${BUILD_NUMBER}
        name: penguin
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}