apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: penguinport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: penguin
  type: LoadBalancer

